---
name: "Media Cleaner"
guid: "607fee77-97eb-41fe-bf22-26844d99ffb0"
version: "2.16.0.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "Delete played media after specified time"
description: >
  Keep your storage clean without hassle.
  Works with movies and series.
category: "General"
owner: "shemanaev"
artifacts:
- "MediaCleaner.dll"
changelog: >
  10.9 compatibility
